name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-iamge:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        versions: [major, minor]
        include:
          - versions: major
            major_secret: MAJOR
          - versions: major
            minor_secret: MINOR
          - dockerfile: ./app/consumer_Dockerfile
            image: bpschmitt/python-consumer:${{ secrets[matrix.major_secret] }}.${{ secrets[matrix.minor_secret] }}
          - dockerfile: ./app/producer_Dockerfile
            image: bpschmitt/python-producer:${{ secrets[matrix.major_secret] }}.${{ secrets[matrix.minor_secret] }}
    permissions:
      contents: read
      packages: write
        
    steps:    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true

    - name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: bpschmitt/confluent-cloud-demo
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
