name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
        
    steps:    
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push consumer Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./app/consumer_Dockerfile
        push: true
        image: bpschmitt/python-consumer:${{ secrets.MAJOR }}.${{ secrets.MINOR }}

    - name: Build and push producer Docker images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./app/producer_Dockerfile
        push: true
        image: bpschmitt/python-producer:${{ secrets.MAJOR }}.${{ secrets.MINOR }}


    - name: Update Minor version
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: 'MINOR'
        value: $((${{ secrets.MINOR }}+1))
        repository: bpschmitt/confluent-cloud-demo
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
